backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "delivery"
    label: "Доставка"
    folder: "src/pages/delivery"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "delivery"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: name, name: name, widget: "string"}
      - {label: "description", name: "description", widget: "string"}
      - {label: Header, name: header, widget: object, fields: [
          {label: Images, name: images, widget: list, fields: [
            {label: Alt, name: alt, widget: string},
            {label: Image, name: image, widget: image}
          ]},
          {label: "Scope information", name: scopeInformation, widget: list, fields: [
            {label: text, name: text, widget: string},
            {label: Image, name: image, widget: image}
          ]},
          {label: Buttons, name: buttons, widget: list, fields: [
            {label: text, name: text, widget: string},
            {label: Link, name: link, widget: string}
          ]}
      ]}
      - {label: "sections", name: "sections", widget: list, fields: [
          {label: "Title", name: "title", widget: "string"},
          {label: "Картинка", name: image, widget: image},
          {label: "Текст", name: text, widget: "markdown"},
          {label: "list", name: list, widget: list, fields: [
            {label: "title", name: title, widget: string},
            {label: "Картинка", name: image, widget: image}
          ]},
      ]}
      - {label: "sectionText", name: "sectionText", widget: object, fields: [
        {label: "Title", name: "title", widget: "string"},
        {label: "Картинка", name: image, widget: image},
        {label: "Текст", name: text, widget: "markdown"},
      ]}
      - {label: Mainpitch, name: mainpitch, widget: object, fields: [
          {label: Article, name: article, widget: "markdown"}
      ]}
  - name: "components"
    label: "Общие компонентны"
    folder: "src/pages/components/"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "components-common"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Calculator", name: calculator, widget: object, fields:[
        {label: "Заголовок", name: title, widget: string},
        {label: "Составляющие цены", name: constituents, widget: list, fields:[
          {label: "Заголовок категории", name: title, widget: string},
          {label: "category", name: category, widget: list, fields:[
            {label: "Название услуги", name: "nameCategory", widget: string},
            {label: "цена", name: "price", widget: number},
            {label: "Картинка", name: image, widget: image}
            ]}
          ]}
        ]}
      - {label: Clients, name: clients, widget: list, fields:[
          {label: image, name: image, widget: image}
        ]}
      - {label: Destinations, name: destinations, widget: object, fields:[
          {label: countries, name: countries, widget: list, fields:[
            {label: country, name: country, widget: string},
            {label: flag, name: flag, widget: image}
          ]},
          {label: image, name: image, widget: image}
      ]}
      - {label: Storage, name: storage, widget: list, fields:[
          {label: country, name: country, widget: string},
          {label: flag, name: flag, widget: image}
        ]}
  - name: "pages"
    label: "Страницы"
    files:
      - file: "src/pages/index.md"
        label: "Главная"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: MetaTitle, name: title, widget: string}
          - {label: MetaDescription, name: description, widget: string}
          - {label: Header, name: header, widget: object, fields: [
              {label: Slide, name: slide, widget: list, fields: [
                {label: Images, name: images, widget: list, fields: [
                  {label: Image, name: image, widget: image},
                  {label: Alt, name: alt, widget: string}
                ]},
                {label: "Scope information", name: scopeInformation, widget: list, fields: [
                  {label: Image, name: image, widget: image},
                  {label: text, name: text, widget: string}
                ]},
                {label: Buttons, name: buttons, widget: list, fields: [
                  {label: Link, name: link, widget: string},
                  {label: text, name: text, widget: string}
                ]}
              ]}
            ]}
          - {label: "Международные перевозки", name: section, widget: object, fields: [
              {label: "Заголовок", name: title, widget: string},
              {label: "Под заголовок", name: subTitle, widget: string},
              {label: "Блоки", name: blocks, widget: list, fields: [
                {label: "Картинка", name: image, widget: image},
                {label: "Текст", name: title, widget: string}
              ]}
          ]}
          - {label: "Про нас", name: about, widget: object, fields: [
              {label: "Заголовок", name: title, widget: string},
              {label: "Текст", name: text, widget: "markdown"},
              {label: "Картинка", name: image, widget: image},
          ]}

          - {label: Mainpitch, name: mainpitch, widget: object, fields: [
            {label: Article, name: article, widget: "markdown"}
          ]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Description, name: description, widget: string},
              {label: Plans, name: plans, widget: list, fields: [
                {label: Plan, name: plan, widget: string},
                {label: Price, name: price, widget: string},
                {label: Description, name: description, widget: string},
                {label: Items, name: items, widget: list}
              ]}
            ]}
      - file: "src/pages/cost-page.md"
        label: "Стоимость"
        name: "cost-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Header, name: header, widget: object, fields: [
              {label: Images, name: images, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: Alt, name: alt, widget: string}
              ]},
              {label: "Scope information", name: scopeInformation, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: text, name: text, widget: string}
              ]},
          ]}
          - {label: "sections", name: "sections", widget: list, fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Картинка", name: image, widget: image},
              {label: "Текст", name: text, widget: "markdown"},
          ]}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [
            {label: Article, name: article, widget: "markdown"}
          ]}
      - file: "src/pages/reviews/index.md"
        label: "Отзывы"
        name: "reviews"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Header, name: header, widget: object, fields: [
              {label: Images, name: images, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: Alt, name: alt, widget: string}
              ]},
              {label: Buttons, name: buttons, widget: list, fields: [
                {label: text, name: text, widget: string},
                {label: Link, name: link, widget: string}
              ]}
          ]}
          - {label: Reviews, name: reviews, widget: list, fields:[
              {label: name, name: name, widget: string},
              {label: text, name: text, widget: markdown},
              {label: date, name: date, widget: string},
              {label: source, name: source, widget: object, fields: [
                {label: name, name: name, widget: string},
                {label: url, name: url, widget: string}
              ]}
          ]}